name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '${{ github.workspace }}/webapp/pom.xml' # optional
           

      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          mvn clean install

      - name: Build Docker Image
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          echo "Building Docker image..."
          sudo docker build -t myweb:2.0 .

      - name: Get Public IP Address
        run: |
          echo "Public IP Address:"
          curl ifconfig.me
          public_ip=$(curl -s ifconfig.me)
          echo "PUBLIC_IP=$public_ip" >> $GITHUB_ENV

      - name: Testing
        run: |
          echo 'Running Tests...'
          ls -la
          docker ps
          sudo docker run -d --name myweb-container -p 8080:8080 myweb:2.0
          sleep 20  # Wait for the server to start
          docker ps
          docker exec myweb-container ls -la /usr/local/tomcat/webapps/
          docker logs myweb-container
          sudo ufw enable
          sudo ufw allow 8080/tcp
          sudo ufw status
          docker inspect myweb-container
          echo "Accessing service at http://localhost:8080/docker-war-demo"
          #http://$PUBLIC_IP:8080/docker-war-demo
          curl http://localhost:8080/docker-war-demo
          sleep 20

          
      - name: Create Tag and push to DockerHub
        run: |
          echo 'Deployment..'
          docker tag myweb:2.0 onkarbhujbal2556/myweb:latest
          docker push onkarbhujbal2556/myweb:2.0
