name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '${{ github.workspace }}/webapp/pom.xml' # optional
           

      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          mvn clean install

      - name: Build Docker Image
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          echo "Building Docker image..."
          sudo docker build -t myweb:2.0 .

      - name: Testing
        run: |
          echo 'Running Tests...'
          ls -la
          docker ps
          sudo docker run -d -p 80:80 myweb:2.0
          
      - name: Deployment
        run: |
          echo 'Deployment..'
          # Add your deployment commands here
