name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '${{ github.workspace }}/webapp/pom.xml' # optional
           

      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          mvn clean install

      - name: Build Docker Image
        run: |
          ls -al
          echo "Building Docker image..."
          sudo docker build -t myweb:2.0 .

      - name: Testing
        run: |
          echo 'Running Tests...'
          ls -la
          sudo cp -rf ./webapp/target/webapp /tmp/myefs/docker_volume/
          sudo docker run -itd --network=my_network --name webserver300${{ github.run_id }} -p 300${{ github.run_id }}:80 myweb:2.0
          sudo docker ps
          curl -kv http://3.139.57.248:300${{ github.run_id }}/index_dev.jsp
          elinks http://3.139.57.248:300${{ github.run_id }}/index.html
          elinks http://3.139.57.248:300${{ github.run_id }}/index.php

      - name: Deployment
        run: |
          echo 'Deployment..'
          # Add your deployment commands here
