name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: '${{ github.workspace }}/webapp/pom.xml' # optional
           

      - name: Build with Maven
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          mvn clean install

      - name: Build Docker Image
        run: |
          cd ${{ github.workspace }}/webapp/
          ls -al
          echo "Building Docker image..."
          sudo docker build -t myweb:2.0 .

      - name: Get Public IP Address
        run: |
          echo "Public IP Address:"
          curl ifconfig.me

      - name: Testing
        run: |
          echo 'Running Tests...'
          ls -la
          docker ps
          sudo docker run -d -p 8080:8080 myweb:2.0
          sleep 20  # Wait for the server to start

          

      - name: Check if application runs
        run: |
          response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080/docker-war-demo/index.html)
          if [ "$response" -ne 200 ]; then
            echo "Index.html is not loading! HTTP status code: $response"
            exit 1
          else
            echo "Index.html is loading successfully! HTTP status code: $response"
          fi
          
      - name: Deployment
        run: |
          echo 'Deployment..'
          # Add your deployment commands here
